# .tbls.yml

# DSN (Database Source Name) to connect database
dsn: sqlite://./test.sqlite

# Path to generate document
# Default is `dbdoc`
docPath: doc/schema

lint:
  duplicateRelations:
    enabled: true
  requireForeignKeyIndex:
    enabled: true
