//! Native decryption of DIG Network capsule resources (docs.dig.net).
//!
//! DIG-minted NFTs carry `data_uris`/`metadata_uris` like
//! `dig://<storeId>:<rootHash>/<resource>` or
//! `urn:dig:chia:<storeId>:<rootHash>/<resource>` (optionally wrapped in an
//! https gateway URL). The bytes served for those URIs are sealed: fetching
//! them over plain HTTP yields ciphertext whose hash can never match the NFT's
//! on-chain `data_hash` (which is over the plaintext). This module implements
//! the client-side recipe so Sage can decrypt locally:
//!
//! 1. Derive the content key from the *rootless* canonical URN via
//!    HKDF-SHA256 — no wallet secret is involved; public-store keys are a pure
//!    function of `(store id, resource key)`.
//! 2. Fetch sealed bytes from a DIG node (`dig.getContent` JSON-RPC, paged).
//! 3. Verify the merkle inclusion proof against the root hash pinned in the
//!    URI (which was anchored on-chain at mint) — never a server-reported root.
//! 4. Split by chunk lengths and open each chunk with AES-256-GCM-SIV
//!    (RFC 8452, fixed zero nonce, no AAD, 16-byte trailing tag).
//!
//! Constants and layout mirror digstore's `digstore-core` crate
//! (`crypto.rs`, `urn.rs`, `merkle.rs`); the unit-test vectors below were
//! generated by that implementation.

use aes_gcm_siv::aead::Aead;
use aes_gcm_siv::{Aes256GcmSiv, Key, KeyInit, Nonce};
use base64::Engine;
use base64::prelude::BASE64_STANDARD;
use hkdf::Hkdf;
use sha2::{Digest, Sha256};
use thiserror::Error;

const HKDF_SALT_DOMAIN: &[u8] = b"digstore-hkdf-salt-v1";
const HKDF_INFO: &[u8] = b"digstore-aes-256-gcm-key-v1";
const MERKLE_NODE_TAG: &[u8] = b"digstore:node:v1";
/// Fixed nonce is safe under GCM-SIV (synthetic IV) and keeps ciphertext
/// deterministic so the on-chain merkle root is reproducible.
const FIXED_NONCE: [u8; 12] = [0u8; 12];
/// Default public read gateway when the URI doesn't name one.
const DEFAULT_RPC_BASE: &str = "https://rpc.dig.net";

#[derive(Debug, Error)]
pub enum DigError {
    #[error("Invalid DIG URI: {0}")]
    InvalidUri(String),

    #[error("URI pins no root hash and no trusted root was supplied")]
    MissingTrustedRoot,

    #[error("DIG node request failed: {0}")]
    Fetch(#[from] reqwest::Error),

    #[error("DIG node returned an error: {0}")]
    Rpc(String),

    #[error("Malformed DIG node response: {0}")]
    Response(String),

    #[error("Merkle inclusion proof failed: {0}")]
    Integrity(&'static str),

    #[error("Chunk lengths do not sum to the ciphertext length")]
    ChunkFraming,

    #[error("Chunk decryption failed (tampered data, wrong key, or missing secret salt)")]
    Decrypt,
}

/// The identifiers extracted from any DIG URI form.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DigUri {
    /// 64-hex store id (lowercase).
    pub store_id: String,
    /// 64-hex root hash (lowercase), if the URI pins a generation.
    pub root_hash: Option<String>,
    /// Resource key within the capsule (no leading slash).
    pub resource_key: String,
    /// Gateway host when the URI was the https fallback form.
    pub gateway: Option<String>,
}

fn is_hex64(s: &str) -> bool {
    s.len() == 64 && s.bytes().all(|b| b.is_ascii_hexdigit())
}

impl DigUri {
    /// Parse any of the three DIG URI forms; `None` if `uri` is not DIG.
    ///
    /// - `dig://<store>:<root>/<resource>`
    /// - `urn:dig:chia:<store>[:<root>]/<resource>`
    /// - `https://<host>/urn:dig:chia:<store>[:<root>]/<resource>`
    pub fn parse(uri: &str) -> Option<Self> {
        let uri = uri.trim();

        if let Some(rest) = uri.strip_prefix("dig://") {
            let (head, resource) = rest.split_once('/')?;
            let (store, root) = head.split_once(':')?;
            return Self::from_parts(store, Some(root), resource, None);
        }

        if let Some(rest) = uri.strip_prefix("urn:dig:chia:") {
            return Self::parse_urn_tail(rest, None);
        }

        // Gateway form: an http(s) URL whose path contains the URN.
        if (uri.starts_with("https://") || uri.starts_with("http://"))
            && let Some(pos) = uri.find("/urn:dig:chia:")
        {
            let gateway = &uri[..pos];
            let tail = &uri[pos + "/urn:dig:chia:".len()..];
            return Self::parse_urn_tail(tail, Some(gateway.to_string()));
        }

        None
    }

    fn parse_urn_tail(tail: &str, gateway: Option<String>) -> Option<Self> {
        let (head, resource) = tail.split_once('/')?;
        match head.split_once(':') {
            Some((store, root)) => Self::from_parts(store, Some(root), resource, gateway),
            None => Self::from_parts(head, None, resource, gateway),
        }
    }

    fn from_parts(
        store: &str,
        root: Option<&str>,
        resource: &str,
        gateway: Option<String>,
    ) -> Option<Self> {
        if !is_hex64(store) || resource.is_empty() {
            return None;
        }
        let root_hash = match root {
            Some(r) if is_hex64(r) => Some(r.to_ascii_lowercase()),
            Some(_) => return None,
            None => None,
        };
        Some(Self {
            store_id: store.to_ascii_lowercase(),
            root_hash,
            resource_key: resource.to_string(),
            gateway,
        })
    }

    /// The ROOT-INDEPENDENT canonical URN — the input to all key derivation.
    /// Keys are stable across store generations; the root hash is only used
    /// as the trusted merkle root.
    pub fn canonical_rootless(&self) -> String {
        format!("urn:dig:chia:{}/{}", self.store_id, self.resource_key)
    }

    /// The key a DIG node uses to look the resource up: SHA-256 of the
    /// rootless canonical URN.
    pub fn retrieval_key(&self) -> [u8; 32] {
        Sha256::digest(self.canonical_rootless().as_bytes()).into()
    }

    /// Derive the AES-256-GCM-SIV content key. Public stores use no salt;
    /// private stores mix a 32-byte secret salt (shared out-of-band) into the
    /// HKDF salt. No wallet key material is involved.
    pub fn derive_key(&self, secret_salt: Option<&[u8; 32]>) -> [u8; 32] {
        let mut salt_hasher = Sha256::new();
        salt_hasher.update(HKDF_SALT_DOMAIN);
        if let Some(secret) = secret_salt {
            salt_hasher.update(secret);
        }
        let salt = salt_hasher.finalize();

        let hk = Hkdf::<Sha256>::new(Some(&salt), self.canonical_rootless().as_bytes());
        let mut okm = [0u8; 32];
        hk.expand(HKDF_INFO, &mut okm)
            .expect("32 is a valid HKDF-SHA256 output length");
        okm
    }
}

/// Split the served ciphertext at `chunk_lens` boundaries and open each chunk.
/// An empty `chunk_lens` means the whole blob is a single sealed chunk.
pub fn decrypt_resource(
    key: &[u8; 32],
    ciphertext: &[u8],
    chunk_lens: &[u32],
) -> Result<Vec<u8>, DigError> {
    let cipher = Aes256GcmSiv::new(Key::<Aes256GcmSiv>::from_slice(key));
    let nonce = Nonce::from_slice(&FIXED_NONCE);

    if chunk_lens.is_empty() {
        return cipher
            .decrypt(nonce, ciphertext)
            .map_err(|_| DigError::Decrypt);
    }

    let total: u64 = chunk_lens.iter().map(|&l| u64::from(l)).sum();
    if total != ciphertext.len() as u64 {
        return Err(DigError::ChunkFraming);
    }

    let mut plaintext = Vec::new();
    let mut offset = 0usize;
    for &len in chunk_lens {
        let end = offset + len as usize;
        let chunk = cipher
            .decrypt(nonce, &ciphertext[offset..end])
            .map_err(|_| DigError::Decrypt)?;
        plaintext.extend_from_slice(&chunk);
        offset = end;
    }
    Ok(plaintext)
}

/// Verify the merkle inclusion proof binding `ciphertext` to `trusted_root`.
///
/// Proof codec (big-endian): `leaf[32] | path_len:u32 | path_len × (hash[32] |
/// is_left:u8) | root[32]`. Leaf = SHA-256 of the whole served ciphertext;
/// node = SHA-256("digstore:node:v1" || left || right).
pub fn verify_inclusion(
    ciphertext: &[u8],
    proof: &[u8],
    trusted_root: &[u8; 32],
) -> Result<(), DigError> {
    let malformed = DigError::Integrity("malformed proof");

    if proof.len() < 32 + 4 + 32 {
        return Err(malformed);
    }
    let leaf: [u8; 32] = proof[0..32].try_into().expect("sliced to 32");
    let path_len = u32::from_be_bytes(proof[32..36].try_into().expect("sliced to 4")) as usize;
    let path_bytes = path_len
        .checked_mul(33)
        .ok_or_else(|| DigError::Integrity("malformed proof"))?;
    if proof.len() != 36 + path_bytes + 32 {
        return Err(malformed);
    }
    let root: [u8; 32] = proof[36 + path_bytes..].try_into().expect("sliced to 32");

    let computed_leaf: [u8; 32] = Sha256::digest(ciphertext).into();
    if computed_leaf != leaf {
        return Err(DigError::Integrity("leaf does not match ciphertext"));
    }

    let mut acc = leaf;
    for i in 0..path_len {
        let step = &proof[36 + i * 33..36 + (i + 1) * 33];
        let sibling: [u8; 32] = step[0..32].try_into().expect("sliced to 32");
        let is_left = step[32] != 0;

        let mut hasher = Sha256::new();
        hasher.update(MERKLE_NODE_TAG);
        if is_left {
            hasher.update(sibling);
            hasher.update(acc);
        } else {
            hasher.update(acc);
            hasher.update(sibling);
        }
        acc = hasher.finalize().into();
    }

    if acc != root {
        return Err(DigError::Integrity("proof does not fold to its root"));
    }
    if &root != trusted_root {
        return Err(DigError::Integrity("proof root is not the trusted root"));
    }
    Ok(())
}

#[derive(serde::Deserialize)]
struct RpcEnvelope {
    result: Option<GetContentResult>,
    error: Option<serde_json::Value>,
}

#[derive(serde::Deserialize)]
struct GetContentResult {
    /// Base64 sealed bytes for this window.
    ciphertext: String,
    /// Base64 merkle proof over the COMPLETE resource ciphertext.
    inclusion_proof: Option<String>,
    /// Per-chunk ciphertext lengths; empty/absent ⇒ single chunk.
    chunk_lens: Option<Vec<u32>>,
    next_offset: Option<u64>,
    complete: Option<bool>,
}

/// Fetch, verify, and decrypt a DIG resource to plaintext.
///
/// The trusted root is taken from the URI when it pins one (for NFT URIs it
/// always does, and that value was anchored on-chain at mint). A rootless URI
/// requires the caller to resolve the store's current root from its Chia
/// singleton and is rejected here.
pub async fn fetch_dig_uri(
    dig: &DigUri,
    secret_salt: Option<&[u8; 32]>,
) -> Result<Vec<u8>, DigError> {
    let trusted_root_hex = dig
        .root_hash
        .as_deref()
        .ok_or(DigError::MissingTrustedRoot)?;
    let mut trusted_root = [0u8; 32];
    hex::decode_to_slice(trusted_root_hex, &mut trusted_root)
        .map_err(|_| DigError::InvalidUri("bad root hash hex".to_string()))?;

    let rpc_base = dig
        .gateway
        .clone()
        .unwrap_or_else(|| DEFAULT_RPC_BASE.to_string());
    let retrieval_key = hex::encode(dig.retrieval_key());

    let client = reqwest::Client::new();
    let mut ciphertext = Vec::new();
    let mut proof_b64: Option<String> = None;
    let mut chunk_lens: Vec<u32> = Vec::new();
    let mut offset: u64 = 0;

    loop {
        let body = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "dig.getContent",
            "params": {
                "store_id": dig.store_id,
                "retrieval_key": retrieval_key,
                "offset": offset,
                "root": trusted_root_hex,
            },
        });

        let envelope: RpcEnvelope = client
            .post(&rpc_base)
            .json(&body)
            .send()
            .await?
            .error_for_status()?
            .json()
            .await?;

        if let Some(error) = envelope.error {
            return Err(DigError::Rpc(error.to_string()));
        }
        let result = envelope
            .result
            .ok_or_else(|| DigError::Response("missing result".to_string()))?;

        let window = BASE64_STANDARD
            .decode(&result.ciphertext)
            .map_err(|e| DigError::Response(format!("bad ciphertext base64: {e}")))?;
        ciphertext.extend_from_slice(&window);

        if let Some(proof) = result.inclusion_proof {
            proof_b64 = Some(proof);
        }
        if let Some(lens) = result.chunk_lens {
            chunk_lens = lens;
        }

        if result.complete.unwrap_or(true) {
            break;
        }
        let next = result.next_offset.ok_or_else(|| {
            DigError::Response("incomplete response without next_offset".to_string())
        })?;
        if next <= offset {
            return Err(DigError::Response("non-advancing next_offset".to_string()));
        }
        offset = next;
    }

    let proof_b64 =
        proof_b64.ok_or_else(|| DigError::Response("missing inclusion proof".to_string()))?;
    let proof = BASE64_STANDARD
        .decode(&proof_b64)
        .map_err(|e| DigError::Response(format!("bad proof base64: {e}")))?;

    verify_inclusion(&ciphertext, &proof, &trusted_root)?;

    let key = dig.derive_key(secret_salt);
    decrypt_resource(&key, &ciphertext, &chunk_lens)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Vectors generated by digstore-core (crates/digstore-core/src/crypto.rs).
    const STORE: &str = "f0b71b1ffc9a6cfdfb774fd4433d962290ec0b844558260157740e24d16608eb";
    const ROOT: &str = "dce977434edd5d28d6fb39b4b60407c53fd7f671b47dba533c73b143c7584ef5";

    fn vector_uri() -> DigUri {
        DigUri::parse(&format!("dig://{STORE}:{ROOT}/IMG_0033.jpeg")).unwrap()
    }

    #[test]
    fn parses_all_uri_forms() {
        let expected = vector_uri();
        let urn = DigUri::parse(&format!("urn:dig:chia:{STORE}:{ROOT}/IMG_0033.jpeg")).unwrap();
        assert_eq!(urn.store_id, expected.store_id);
        assert_eq!(urn.root_hash, expected.root_hash);
        assert_eq!(urn.resource_key, "IMG_0033.jpeg");

        let gw = DigUri::parse(&format!(
            "https://rpc.dig.net/urn:dig:chia:{STORE}:{ROOT}/metadata/IMG_0033.jpeg.json"
        ))
        .unwrap();
        assert_eq!(gw.gateway.as_deref(), Some("https://rpc.dig.net"));
        assert_eq!(gw.resource_key, "metadata/IMG_0033.jpeg.json");

        let rootless = DigUri::parse(&format!("urn:dig:chia:{STORE}/index.html")).unwrap();
        assert_eq!(rootless.root_hash, None);

        assert!(DigUri::parse("https://example.com/image.png").is_none());
        assert!(DigUri::parse("dig://not-hex/resource").is_none());
    }

    #[test]
    fn derives_retrieval_key_and_content_keys() {
        let uri = vector_uri();
        assert_eq!(
            uri.canonical_rootless(),
            format!("urn:dig:chia:{STORE}/IMG_0033.jpeg"),
            "keys derive from the ROOTLESS canonical URN"
        );
        assert_eq!(
            hex::encode(uri.retrieval_key()),
            "41db84d332b11f6ce14b7f1e0c7739a811f0746a09830655f399f2dbeb29a9d0"
        );
        assert_eq!(
            hex::encode(uri.derive_key(None)),
            "cc3a8d77cca46af6ec13294d42fd4c776f4545b86753a0f265a52ffa3922511b"
        );
        let salt: [u8; 32] = core::array::from_fn(|i| i as u8);
        assert_eq!(
            hex::encode(uri.derive_key(Some(&salt))),
            "d8a2bbc2c90e5c2cdb8cee81ba1c7e471f63761de9f6ac91d26bdd61ef49c0f0"
        );
    }

    #[test]
    fn decrypts_digstore_vector() {
        let uri = vector_uri();
        let key = uri.derive_key(None);
        let ciphertext = hex::decode("5b28514197c43b3056d364bb3eafac1eada4ac1aebfacf3974").unwrap();
        assert_eq!(
            decrypt_resource(&key, &ciphertext, &[]).unwrap(),
            b"hello dig"
        );
        // Multi-chunk framing: same blob declared as one explicit chunk.
        assert_eq!(
            decrypt_resource(&key, &ciphertext, &[ciphertext.len() as u32]).unwrap(),
            b"hello dig"
        );
        // Tampered ciphertext fails authentication.
        let mut tampered = ciphertext;
        tampered[0] ^= 1;
        assert!(matches!(
            decrypt_resource(&key, &tampered, &[]),
            Err(DigError::Decrypt)
        ));
    }

    #[test]
    fn merkle_node_hash_matches_digstore() {
        // node(aa*32, bb*32) vector from digstore-core.
        let mut hasher = Sha256::new();
        hasher.update(MERKLE_NODE_TAG);
        hasher.update([0xaa; 32]);
        hasher.update([0xbb; 32]);
        let node: [u8; 32] = hasher.finalize().into();
        assert_eq!(
            hex::encode(node),
            "e8fee844602e5d97b13aaea2cdc344c8355f7763553a093030bd31785a71b2cd"
        );
    }

    #[test]
    fn verifies_single_step_inclusion_proof() {
        let ciphertext = b"sealed bytes";
        let leaf: [u8; 32] = Sha256::digest(ciphertext).into();
        let sibling = [0x11u8; 32];

        let mut hasher = Sha256::new();
        hasher.update(MERKLE_NODE_TAG);
        hasher.update(leaf);
        hasher.update(sibling);
        let root: [u8; 32] = hasher.finalize().into();

        let mut proof = Vec::new();
        proof.extend_from_slice(&leaf);
        proof.extend_from_slice(&1u32.to_be_bytes());
        proof.extend_from_slice(&sibling);
        proof.push(0); // sibling is on the right
        proof.extend_from_slice(&root);

        verify_inclusion(ciphertext, &proof, &root).unwrap();
        assert!(verify_inclusion(b"other bytes", &proof, &root).is_err());
        assert!(verify_inclusion(ciphertext, &proof, &[0u8; 32]).is_err());
    }
}
